# Generated by Django 5.0.3 on 2024-04-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_id_alter_artist_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, upload_to='genres/'),
        ),
    ]
