# Generated by Django 5.0.3 on 2024-04-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_uploadedsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
    ]
